services:
  devcontainer:
    container_name: exporter
    image: mcr.microsoft.com/dotnet/sdk:7.0-alpine3.18
    entrypoint: /bin/sh /run.sh
    working_dir: /app
    volumes:
      - "${DOCKER_SOCK}:/var/run/docker.sock"
      - "./run.sh:/run.sh"
      - "../src:/app"
    ports:
      - "18085:18085"
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    ports:
      - "9090:9090"
    command: --config.file=/etc/prometheus/prometheus.yml
volumes:
  prometheus-data:
