services:
  devcontainer:
    container_name: exporter_dev
    image: mcr.microsoft.com/dotnet/sdk:7.0-alpine3.18
    entrypoint: /bin/sh /run.sh
    working_dir: /app
    volumes:
      - "${DOCKER_SOCK}:/var/run/docker.sock"
      - "./run.sh:/run.sh"
      - "../src:/app"
    ports:
      - 9001:9001
